### ISSUE TITLE
TypeError: write_recording() got an unexpected keyword argument 'write_as_lfp'

### ISSUE THREAD

**Issue by rf13734** [catalystneuro/mease-lab-to-nwb#35]
@luiztauffer  Got this error when trying to quick_write, might this be a carry-over of previous dimension error issues?

![image](https://user-images.githubusercontent.com/43117750/118666038-20ca5900-b7f3-11eb-8bd4-02aa3d2318e0.png)

![image](https://user-images.githubusercontent.com/43117750/118666379-6d159900-b7f3-11eb-91b4-aa92b1f67b53.png)

Many thanks in advance!

**Comment by luiztauffer** [comment]
@rf13734 oh yes, this is a recent change on `nwb-conversion-tools`, I will update it here to use it properly

**Comment by rf13734** [comment]
@luiztauffer @alejoe91 I updated spikeextractors and spiketoolkits, but still get the issue, not sure if this is predicted at this time? 

![image](https://user-images.githubusercontent.com/43117750/119141661-d42a8c00-ba45-11eb-9c0d-f980e301b9bb.png)

**Comment by luiztauffer** [comment]
@rf13734  I’m sorry for all those errors, we have the nwb-conversion-tools (and its interface with SpikeExtractors) under heavy development right now, so somethings are likely to break… and thanks a lot for reporting the errors, this helps us immensely in this phase! 
I'm working on the fix for this one now
